### ISSUE TITLE
"students who received" for a specific ta grading mark broken for team assignments

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#1794]
(clicking on the people icon next to the mark from the ta interface)
for example, it just lists "null, null, null" instead of the 3 teams who received that mark.

**Comment by KevinMackenzie** [comment]
I'm not sure if this is being fixed with some of the other TA grading interface changes, but it looks like this is failing because the line 
```
$graded_components = $this->core->getQueries()->getGradedComponentsCountByGradingSections($gradeable_id, $sections, $section_key, $team);
```
contains the variable `$team` which doesn't exist in the scope.

**Comment by CouleeApps** [comment]
#2061 fixes the syntax error, but this still happens: ![](https://i.imgur.com/O1bteDQ.jpg)
